app:
  myport: ${PORT:0}
server:
  port: ${app.myport}
spring:
  profiles:
    active: docker
  application:
    name: servicos-service
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:h2:mem:servicos
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true

  datasource:
    #    url: jdbc:mysql://localhost:3306/servicos
    url: jdbc:mysql://mysql-server:3306/servicos
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/